version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":arrow_up: deps:"
      include: "scope"
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":arrow_up: docs:"
      include: "scope"
