abbreviations = {
    "en": {
        "lol": "laughing out loud",
        "brb": "be right back",
        "omg": "oh my god",
        "btw": "by the way",
        "idk": "I don't know",
        "gtg": "got to go",
        "fyi": "for your information",
        "wtf": "what the fuck",
        "afk": "away from keyboard",
        "bff": "best friends forever",
        "imho": "in my humble opinion",
        "irl": "in real life",
        "rofl": "rolling on the floor laughing",
        "thx": "thanks",
        "ttyl": "talk to you later",
        "omw": "on my way",
        "wb": "welcome back",
        "ty": "thank you",
        "yolo": "you only live once",
        "imo": "in my opinion",
        "jk": "just kidding",
        "idc": "I don't care",
        "smh": "shaking my head",
        "tbh": "to be honest",
        "lmk": "let me know",
        "gr8": "great",
        "rn": "right now",
        "pls": "please",
        "tho": "though",
        "gg": "good game",
        "afaik": "as far as I know",
        "bfn": "bye for now",
        "dw": "don't worry",
        "fomo": "fear of missing out",
        "hmu": "hit me up",
        "icymi": "in case you missed it",
        "jic": "just in case",
        "lmao": "laughing my ass off",
        "np": "no problem",
        "nvm": "never mind",
        "oml": "oh my lord",
        "pov": "point of view",
        "smdh": "shaking my damn head",
        "tbt": "throwback Thursday",
        "tgif": "thank god it's Friday",
        "til": "today I learned",
        "tmi": "too much information",
        "wbu": "what about you",
        "wth": "what the hell",
        "yw": "you're welcome"
    },
    "fr": {
        "bjr": "bonjour",
        "slt": "salut",
        "mdr": "mort de rire",
        "cc": "coucou",
        "svp": "s'il vous plaît",
        "mercii": "merci",
        "stp": "s'il te plaît",
        "bcp": "beaucoup",
        "tg": "ta gueule",
        "pk": "pourquoi",
        "psq": "parce que",
        "dsl": "désolé",
        "bsr": "bonsoir",
        "ok": "d'accord",
        "rdv": "rendez-vous",
        "aprem": "après-midi",
        "a+": "à plus",
        "koi": "quoi",
        "jtm": "je t'aime",
        "stv": "ça va",
        "bsx": "bisous",
        "pkoi": "pourquoi",
        "pkpas": "pourquoi pas",
        "ptdr": "pété de rire",
        "wsh": "qu'est-ce qu'il se passe",
        "jpp": "j'en peux plus",
        "bis": "bises",
        "tkt": "t'inquiète"
    }
}
