default_install_hook_types: [pre-commit, commit-msg]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.4.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['commitlint-config-gitmoji']
