# DO NOT EDIT THIS FILE!
 
class bot():

    token            = None
    default_prefix   = "!"
    default_language = "en"
    bot_admins       = [279568324260528128,125722240896598016] # (Default: Leirof & Z_runner, the project leaders of Gipsy)
    errors_channel   = 823813751018487848                      # (Default: Hidden channel on Gunivers)

################################################################################
# Plugin config


# rss
class rss():

    twitter = {
        "consumer_key": "",
        "consumer_secret": "",
        "access_token_key": "",
        "access_token_secret": ""
    }

    rss_loop_enabled = True