bot:
    token: null
    default_prefix: "!"
    default_language: "en"
    admins: [279568324260528128,125722240896598016] # (Default: Leirof & Z_runner, the project leaders of Gipsy)
    error_channels: 823813751018487848                  # (Default: Hidden channel on Gunivers)

